# Generated by Django 4.1.10 on 2023-09-01 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('dashboard_uid', models.CharField(max_length=50, unique=True)),
                ('dashboard_slug', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GrafanaServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panel_id', models.IntegerField()),
                ('panel_title', models.CharField(default='', max_length=100)),
                ('embed_url', models.URLField(default='', max_length=500)),
                ('time_range', models.CharField(default='3h', max_length=100)),
                ('custom_time_range', models.CharField(blank=True, max_length=100, null=True)),
                ('selected', models.BooleanField(default=False)),
                ('slide_interval', models.PositiveIntegerField(default=0)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boards', to='grfn_app.dashboard')),
            ],
            options={
                'unique_together': {('panel_id', 'dashboard')},
            },
        ),
    ]
